### ISSUE TITLE
Transform json-api payloads back to plain old javascript objects

### ISSUE THREAD

**Issue by powell0** [GaiamTV/transformalizer#20]
@cludden Do you have any plans to add functionality to transform json-api payloads back to plain old javascript objects?

If you don't have plans but would be interested in having that kind of functionality I'd be happy to work on developing that kind of feature as that is something I'd love to have in the library.

**Comment by cludden** [comment]
@powell0 I do not have plans at the moment, but would definitely welcome your help on a feature like that!
